create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  image_url text,
  meal_type text not null,
  goal text not null,
  calories integer not null check (calories > 0),
  protein_g numeric(8,1) not null default 0,
  fat_g numeric(8,1) not null default 0,
  carbs_g numeric(8,1) not null default 0,
  prep_minutes integer,
  ingredients jsonb not null default '[]'::jsonb,
  steps jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.recipes enable row level security;
grant select on table public.recipes to authenticated;
revoke insert, update, delete on table public.recipes from authenticated, anon;

drop policy if exists recipes_read_active on public.recipes;
create policy recipes_read_active on public.recipes
for select to authenticated
using (is_active = true);

-- Initial catalog seed. IDs are generated by PostgreSQL and recipes are upserted by slug.
insert into public.recipes (slug,title,image_url,meal_type,goal,calories,protein_g,fat_g,carbs_g,prep_minutes,ingredients,steps,sort_order)
values
('omelet-tomatoes-spinach','Омлет с томатами и шпинатом','https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80','Завтрак','Поддержание',360,27,21,15,15,
 '["3 яйца","80 г томатов черри","50 г свежего шпината","30 г мягкого сыра","1 ч. л. оливкового масла","Соль и перец по вкусу"]'::jsonb,
 '["Разогрейте сковороду на среднем огне и добавьте оливковое масло.","Разрежьте томаты пополам и прогрейте 2–3 минуты.","Добавьте шпинат и готовьте ещё около минуты, пока он не уменьшится в объёме.","Взбейте яйца с солью и перцем, влейте на сковороду.","Добавьте сыр и готовьте под крышкой 4–5 минут до желаемой степени готовности."]'::jsonb,10),
('turkey-bulgur-bowl','Боул с индейкой и булгуром','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80','Обед','Набор',585,46,18,61,30,
 '["170 г филе индейки","70 г сухого булгура","120 г огурца","120 г томатов","50 г салатных листьев","40 г греческого йогурта","1 ч. л. оливкового масла","Соль, паприка и лимонный сок"]'::jsonb,
 '["Отварите булгур согласно инструкции до готовности.","Нарежьте индейку, приправьте паприкой и солью, обжарьте до полной готовности.","Нарежьте огурец и томаты, подготовьте салатные листья.","Смешайте йогурт с лимонным соком и щепоткой соли.","Соберите боул: булгур, овощи, индейка и йогуртовый соус. Сверху добавьте оливковое масло."]'::jsonb,20),
('cottage-cheese-berry-bowl','Творожная чаша с ягодами','https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=80','Перекус','Похудение',325,32,9,30,7,
 '["200 г творога 2–5%","100 г греческого йогурта","100 г ягод","10 г миндаля","1 ч. л. мёда или подсластитель по вкусу"]'::jsonb,
 '["Выложите творог в глубокую миску.","Добавьте греческий йогурт и перемешайте до кремовой текстуры.","Добавьте ягоды.","Посыпьте измельчённым миндалём.","При желании добавьте мёд или подсластитель и подавайте сразу."]'::jsonb,30)
on conflict (slug) do update set
  title=excluded.title,
  image_url=excluded.image_url,
  meal_type=excluded.meal_type,
  goal=excluded.goal,
  calories=excluded.calories,
  protein_g=excluded.protein_g,
  fat_g=excluded.fat_g,
  carbs_g=excluded.carbs_g,
  prep_minutes=excluded.prep_minutes,
  ingredients=excluded.ingredients,
  steps=excluded.steps,
  is_active=true,
  sort_order=excluded.sort_order,
  updated_at=now();